apiVersion: petstore.example.com/v1alpha1
kind: Pet
metadata:
  labels:
    app.kubernetes.io/name: pet
    app.kubernetes.io/instance: pet-sample
    app.kubernetes.io/part-of: petstore-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: petstore-operator
  name: pet-sample
spec:
  # TODO(user): Add fields here
